"""Download helpers for offline cache under cache/datasets/."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from paths import DATASETS_DIR


def download_source(source: str) -> None:
    """Best-effort download. Many sources need git/HF; we document + create stubs."""
    out = DATASETS_DIR / source
    out.mkdir(parents=True, exist_ok=True)
    readme = out / "README_DOWNLOAD.md"
    urls = {
        "cyberseceval": "https://github.com/meta-llama/PurpleLlama (CybersecurityBenchmarks/datasets/)",
        "wildguard": "https://huggingface.co/datasets/allenai/wildguardmix (gated)",
        "harmbench": "https://github.com/centerforaisafety/HarmBench data/behavior_datasets/harmbench_behaviors_text_all.csv",
        "llmail": "https://huggingface.co/datasets/microsoft/llmail-inject-challenge",
        "bipia": "https://github.com/microsoft/BIPIA",
        "injecagent": "https://github.com/uiuc-kang-lab/InjecAgent",
        "agentdojo": "https://github.com/ethz-spylab/agentdojo",
        "tensortrust": "https://github.com/HumanCompatibleAI/tensor-trust-data",
        "asb": "https://github.com/agiresearch/ASB",
        "xstest": "https://github.com/paul-rottger/exaggerated-safety",
        "orbench": "https://huggingface.co/datasets/bench-llm/or-bench",
        "multilingual": "MultiJail + PolyGuardPrompts on HF",
        "wmdp": "https://huggingface.co/datasets/cais/wmdp (gated)",
        "selfbuild": "generated by adapters.selfbuild (no download)",
    }
    text = (
        f"# {source}\n\n"
        f"Place raw files here for the adapter to pick up.\n\n"
        f"Upstream: {urls.get(source, 'see objective doc')}\n"
    )
    readme.write_text(text, encoding="utf-8")
    if source == "selfbuild":
        from adapters.selfbuild import SelfBuildAdapter

        ad = SelfBuildAdapter()
        for subset, n in [
            ("canary", 100),
            ("ssrf", 50),
            ("pii", 50),
            ("longctx", 200),
            ("repeat_bomb", 100),
            ("sponge", 50),
            ("longdoc_benign", 50),
        ]:
            ad.ensure_static(subset, n)
            print(f"generated selfbuild/{subset}")
    print(f"[download] prepared {out}")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="python -m adapters.download")
    p.add_argument("--source", nargs="+", required=True)
    args = p.parse_args(argv)
    for s in args.source:
        download_source(s)
    return 0


if __name__ == "__main__":
    sys.exit(main())
